import {
  User,
  Doctor,
  Patient,
  Appointment,
  MedicalRecord,
  Invoice,
  AuditLog,
} from '../types';

export const initialUsers: User[] = [
  {
    id: 'user-admin',
    email: 'administrator@example.test',
    role: 'administrator',
    fullName: 'Dr. Evelyn Vance, MD',
    isActive: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'user-doc-1',
    email: 'doctor@example.test',
    role: 'doctor',
    fullName: 'Dr. Sarah Jenkins',
    isActive: true,
    createdAt: '2026-01-12T09:00:00Z',
    updatedAt: '2026-01-12T09:00:00Z',
  },
  {
    id: 'user-recep',
    email: 'receptionist@example.test',
    role: 'receptionist',
    fullName: 'Marcus Sterling',
    isActive: true,
    createdAt: '2026-01-15T08:30:00Z',
    updatedAt: '2026-01-15T08:30:00Z',
  },
  {
    id: 'user-pat-1',
    email: 'patient@example.test',
    role: 'patient',
    fullName: 'Eleanor Bennett',
    isActive: true,
    createdAt: '2026-02-01T10:15:00Z',
    updatedAt: '2026-02-01T10:15:00Z',
  },
];

export const initialDoctors: Doctor[] = [
  {
    id: 'doc-1',
    userId: 'user-doc-1',
    fullName: 'Dr. Sarah Jenkins',
    email: 'doctor@example.test',
    departmentId: 'dept-1',
    departmentName: 'Cardiology',
    specialization: 'Interventional Cardiology & Preventive Care',
    qualification: 'MD, FACC, Harvard Medical School',
    experienceYears: 14,
    consultationFee: 150,
    roomNumber: 'Room 304 - Wing A',
    contactNumber: '+1 (555) 234-5678',
    avatarColor: 'blue',
    isActive: true,
    availability: [
      { id: 'av-1', doctorId: 'doc-1', dayOfWeek: 'Monday', startTime: '09:00', endTime: '13:00', slotDurationMinutes: 30, isActive: true },
      { id: 'av-2', doctorId: 'doc-1', dayOfWeek: 'Tuesday', startTime: '09:00', endTime: '13:00', slotDurationMinutes: 30, isActive: true },
      { id: 'av-3', doctorId: 'doc-1', dayOfWeek: 'Wednesday', startTime: '14:00', endTime: '17:00', slotDurationMinutes: 30, isActive: true },
      { id: 'av-4', doctorId: 'doc-1', dayOfWeek: 'Friday', startTime: '09:00', endTime: '12:00', slotDurationMinutes: 30, isActive: true },
    ],
  },
  {
    id: 'doc-2',
    userId: 'user-doc-2',
    fullName: 'Dr. Michael Chen',
    email: 'm.chen@hospital.test',
    departmentId: 'dept-2',
    departmentName: 'Neurology',
    specialization: 'Cognitive Disorders & Neuro-Oncology',
    qualification: 'MD, PhD, Johns Hopkins Medicine',
    experienceYears: 11,
    consultationFee: 180,
    roomNumber: 'Room 412 - Wing B',
    contactNumber: '+1 (555) 345-6789',
    avatarColor: 'purple',
    isActive: true,
    availability: [
      { id: 'av-5', doctorId: 'doc-2', dayOfWeek: 'Monday', startTime: '10:00', endTime: '14:00', slotDurationMinutes: 30, isActive: true },
      { id: 'av-6', doctorId: 'doc-2', dayOfWeek: 'Thursday', startTime: '10:00', endTime: '15:00', slotDurationMinutes: 30, isActive: true },
    ],
  },
  {
    id: 'doc-3',
    userId: 'user-doc-3',
    fullName: 'Dr. Amara Patel',
    email: 'a.patel@hospital.test',
    departmentId: 'dept-3',
    departmentName: 'Pediatrics',
    specialization: 'Neonatal & Child Wellness Care',
    qualification: 'MD, FAAP, Stanford University',
    experienceYears: 9,
    consultationFee: 120,
    roomNumber: 'Room 108 - Wing C',
    contactNumber: '+1 (555) 456-7890',
    avatarColor: 'yellow',
    isActive: true,
    availability: [
      { id: 'av-7', doctorId: 'doc-3', dayOfWeek: 'Monday', startTime: '09:00', endTime: '15:00', slotDurationMinutes: 30, isActive: true },
      { id: 'av-8', doctorId: 'doc-3', dayOfWeek: 'Wednesday', startTime: '09:00', endTime: '14:00', slotDurationMinutes: 30, isActive: true },
      { id: 'av-9', doctorId: 'doc-3', dayOfWeek: 'Friday', startTime: '09:00', endTime: '13:00', slotDurationMinutes: 30, isActive: true },
    ],
  },
  {
    id: 'doc-4',
    userId: 'user-doc-4',
    fullName: 'Dr. Robert Alverez',
    email: 'r.alverez@hospital.test',
    departmentId: 'dept-4',
    departmentName: 'Orthopedics',
    specialization: 'Joint Reconstruction & Sports Medicine',
    qualification: 'MS Ortho, Mayo Clinic College',
    experienceYears: 16,
    consultationFee: 160,
    roomNumber: 'Room 214 - Wing A',
    contactNumber: '+1 (555) 567-8901',
    avatarColor: 'teal',
    isActive: true,
    availability: [
      { id: 'av-10', doctorId: 'doc-4', dayOfWeek: 'Tuesday', startTime: '09:00', endTime: '14:00', slotDurationMinutes: 30, isActive: true },
      { id: 'av-11', doctorId: 'doc-4', dayOfWeek: 'Thursday', startTime: '13:00', endTime: '17:00', slotDurationMinutes: 30, isActive: true },
    ],
  },
  {
    id: 'doc-5',
    userId: 'user-doc-5',
    fullName: 'Dr. Linda O\'Connor',
    email: 'l.oconnor@hospital.test',
    departmentId: 'dept-5',
    departmentName: 'General Medicine',
    specialization: 'Internal Medicine & Chronic Disease Management',
    qualification: 'MD, University of Pennsylvania',
    experienceYears: 18,
    consultationFee: 100,
    roomNumber: 'OPD Desk 3',
    contactNumber: '+1 (555) 678-9012',
    avatarColor: 'green',
    isActive: true,
    availability: [
      { id: 'av-12', doctorId: 'doc-5', dayOfWeek: 'Monday', startTime: '09:00', endTime: '17:00', slotDurationMinutes: 30, isActive: true },
      { id: 'av-13', doctorId: 'doc-5', dayOfWeek: 'Tuesday', startTime: '09:00', endTime: '17:00', slotDurationMinutes: 30, isActive: true },
      { id: 'av-14', doctorId: 'doc-5', dayOfWeek: 'Wednesday', startTime: '09:00', endTime: '17:00', slotDurationMinutes: 30, isActive: true },
    ],
  },
];

export const initialPatients: Patient[] = [
  {
    id: 'pat-1',
    userId: 'user-pat-1',
    mrn: 'MRN-2026-001',
    fullName: 'Eleanor Bennett',
    dateOfBirth: '1988-04-14',
    gender: 'female',
    bloodGroup: 'O+',
    contactNumber: '+1 (555) 912-3456',
    email: 'patient@example.test',
    address: '742 Evergreen Terrace, Springfield',
    emergencyContact: {
      name: 'Thomas Bennett',
      relationship: 'Spouse',
      phone: '+1 (555) 912-3499',
    },
    allergies: ['Penicillin', 'Sulfa drugs'],
    medicalHistorySummary: 'Hypertension diagnosed 2021, controlled via lifestyle and ACE inhibitors.',
    createdAt: '2026-01-14T10:00:00Z',
    updatedAt: '2026-01-14T10:00:00Z',
  },
  {
    id: 'pat-2',
    mrn: 'MRN-2026-002',
    fullName: 'James Alexander Davis',
    dateOfBirth: '1975-11-23',
    gender: 'male',
    bloodGroup: 'A+',
    contactNumber: '+1 (555) 834-1290',
    email: 'j.davis@consumer.test',
    address: '104 Oakridge Crescent, Metro City',
    emergencyContact: {
      name: 'Claire Davis',
      relationship: 'Sister',
      phone: '+1 (555) 834-1291',
    },
    allergies: ['Aspirin'],
    medicalHistorySummary: 'Type 2 Diabetes mellitus, mild lumbar disc degeneration.',
    createdAt: '2026-01-18T11:20:00Z',
    updatedAt: '2026-01-18T11:20:00Z',
  },
  {
    id: 'pat-3',
    mrn: 'MRN-2026-003',
    fullName: 'Sophia Maria Ramirez',
    dateOfBirth: '2001-08-05',
    gender: 'female',
    bloodGroup: 'B-',
    contactNumber: '+1 (555) 723-8841',
    email: 'sophia.ramirez@consumer.test',
    address: '512 Harbor Boulevard, Metro City',
    emergencyContact: {
      name: 'Carlos Ramirez',
      relationship: 'Father',
      phone: '+1 (555) 723-8800',
    },
    allergies: [],
    medicalHistorySummary: 'Seasonal allergic rhinitis, no chronic pathologies.',
    createdAt: '2026-02-02T14:15:00Z',
    updatedAt: '2026-02-02T14:15:00Z',
  },
  {
    id: 'pat-4',
    mrn: 'MRN-2026-004',
    fullName: 'William Harrison Vance',
    dateOfBirth: '1962-02-17',
    gender: 'male',
    bloodGroup: 'AB+',
    contactNumber: '+1 (555) 645-3129',
    email: 'w.vance@consumer.test',
    address: '88 Meadowbrook Lane, Springfield',
    emergencyContact: {
      name: 'Martha Vance',
      relationship: 'Spouse',
      phone: '+1 (555) 645-3100',
    },
    allergies: ['Codeine'],
    medicalHistorySummary: 'Post-CABG surgery in 2022, routine cardiology follow-up.',
    createdAt: '2026-02-10T09:40:00Z',
    updatedAt: '2026-02-10T09:40:00Z',
  },
];

export const initialAppointments: Appointment[] = [
  {
    id: 'apt-101',
    patientId: 'pat-1',
    patientName: 'Eleanor Bennett',
    patientMrn: 'MRN-2026-001',
    doctorId: 'doc-1',
    doctorName: 'Dr. Sarah Jenkins',
    departmentName: 'Cardiology',
    appointmentDate: new Date().toISOString().split('T')[0], // Today
    startTime: '09:30',
    endTime: '10:00',
    status: 'scheduled',
    reason: 'Quarterly cardiovascular review and blood pressure assessment',
    type: 'consultation',
    createdByRole: 'patient',
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
  },
  {
    id: 'apt-102',
    patientId: 'pat-2',
    patientName: 'James Alexander Davis',
    patientMrn: 'MRN-2026-002',
    doctorId: 'doc-4',
    doctorName: 'Dr. Robert Alverez',
    departmentName: 'Orthopedics',
    appointmentDate: new Date().toISOString().split('T')[0], // Today
    startTime: '10:30',
    endTime: '11:00',
    status: 'scheduled',
    reason: 'Follow-up on lower back physiotherapy regimen',
    type: 'follow_up',
    createdByRole: 'receptionist',
    createdAt: '2026-09-21T09:15:00Z',
    updatedAt: '2026-09-21T09:15:00Z',
  },
  {
    id: 'apt-103',
    patientId: 'pat-3',
    patientName: 'Sophia Maria Ramirez',
    patientMrn: 'MRN-2026-003',
    doctorId: 'doc-5',
    doctorName: 'Dr. Linda O\'Connor',
    departmentName: 'General Medicine',
    appointmentDate: new Date().toISOString().split('T')[0], // Today
    startTime: '11:00',
    endTime: '11:30',
    status: 'scheduled',
    reason: 'Persistent fatigue, sore throat and seasonal allergies',
    type: 'consultation',
    createdByRole: 'receptionist',
    createdAt: '2026-09-22T11:45:00Z',
    updatedAt: '2026-09-22T11:45:00Z',
  },
  {
    id: 'apt-104',
    patientId: 'pat-4',
    patientName: 'William Harrison Vance',
    patientMrn: 'MRN-2026-004',
    doctorId: 'doc-1',
    doctorName: 'Dr. Sarah Jenkins',
    departmentName: 'Cardiology',
    appointmentDate: '2026-09-18',
    startTime: '11:30',
    endTime: '12:00',
    status: 'completed',
    reason: 'Post-CABG stress ECG interpretation and statin check',
    type: 'routine_checkup',
    createdByRole: 'administrator',
    createdAt: '2026-09-10T14:20:00Z',
    updatedAt: '2026-09-18T12:05:00Z',
  },
  {
    id: 'apt-105',
    patientId: 'pat-1',
    patientName: 'Eleanor Bennett',
    patientMrn: 'MRN-2026-001',
    doctorId: 'doc-2',
    doctorName: 'Dr. Michael Chen',
    departmentName: 'Neurology',
    appointmentDate: '2026-09-15',
    startTime: '14:00',
    endTime: '14:30',
    status: 'completed',
    reason: 'Occasional vestibular dizziness and migraine prophylaxis review',
    type: 'consultation',
    createdByRole: 'patient',
    createdAt: '2026-09-08T09:30:00Z',
    updatedAt: '2026-09-15T14:40:00Z',
  },
];

export const initialMedicalRecords: MedicalRecord[] = [
  {
    id: 'rec-201',
    appointmentId: 'apt-104',
    patientId: 'pat-4',
    patientName: 'William Harrison Vance',
    doctorId: 'doc-1',
    doctorName: 'Dr. Sarah Jenkins',
    doctorSpecialization: 'Interventional Cardiology',
    recordDate: '2026-09-18',
    vitals: {
      bloodPressure: '124/78 mmHg',
      heartRate: 68,
      temperature: 36.7,
      weightKg: 82.5,
      oxygenSaturation: 99,
    },
    symptoms: 'Reports good exercise tolerance walking 45 mins daily without chest discomfort or shortness of breath.',
    diagnosis: 'Stable ischemic heart disease status-post coronary artery bypass grafting; well-controlled dyslipidemia.',
    consultationNotes: 'Stress ECG shows no signs of inducible myocardial ischemia. Lipid panel demonstrates LDL cholesterol at 64 mg/dL. Continue current medical regimen and regular cardiac exercise.',
    prescriptions: [
      { id: 'rx-1', medicineName: 'Atorvastatin', dosage: '40mg', frequency: 'Once daily at bedtime', duration: '90 days', instructions: 'Take with or without food' },
      { id: 'rx-2', medicineName: 'Metoprolol Succinate ER', dosage: '50mg', frequency: 'Once daily in the morning', duration: '90 days', instructions: 'Do not crush or chew' },
      { id: 'rx-3', medicineName: 'Aspirin (Enteric-coated)', dosage: '81mg', frequency: 'Once daily with meals', duration: '90 days', instructions: 'Cardioprotective low dose' },
    ],
    followUpDate: '2026-12-18',
    createdAt: '2026-09-18T12:00:00Z',
  },
  {
    id: 'rec-202',
    appointmentId: 'apt-105',
    patientId: 'pat-1',
    patientName: 'Eleanor Bennett',
    doctorId: 'doc-2',
    doctorName: 'Dr. Michael Chen',
    doctorSpecialization: 'Neurology',
    recordDate: '2026-09-15',
    vitals: {
      bloodPressure: '118/74 mmHg',
      heartRate: 72,
      temperature: 36.6,
      weightKg: 64.0,
      oxygenSaturation: 98,
    },
    symptoms: 'Episodic pulsating unilateral headache with photophobia approximately 2 times monthly.',
    diagnosis: 'Common migraine without aura (ICD-10 G43.009).',
    consultationNotes: 'Cranial nerve exam normal. No focal motor or sensory deficits. Recommend hydration, sleep hygiene, and trial of Sumatriptan at acute onset.',
    prescriptions: [
      { id: 'rx-4', medicineName: 'Sumatriptan Tablets', dosage: '50mg', frequency: 'As needed at migraine onset', duration: '10 doses', instructions: 'May repeat once after 2 hours if required' },
      { id: 'rx-5', medicineName: 'Magnesium Glycinate', dosage: '400mg', frequency: 'Nightly', duration: '60 days', instructions: 'Nutritional prophylaxis support' },
    ],
    followUpDate: '2026-11-15',
    createdAt: '2026-09-15T14:35:00Z',
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv-301',
    invoiceNumber: 'INV-2026-101',
    appointmentId: 'apt-104',
    patientId: 'pat-4',
    patientName: 'William Harrison Vance',
    doctorName: 'Dr. Sarah Jenkins',
    subtotal: 150,
    additionalCharges: 75, // ECG diagnostic interpretation
    discount: 0,
    totalAmount: 225,
    paymentStatus: 'paid',
    paymentMethod: 'credit_card',
    paidAt: '2026-09-18T12:20:00Z',
    dueDate: '2026-09-18',
    items: [
      { id: 'item-1', description: 'Cardiology Specialist Consultation', quantity: 1, unitPrice: 150, lineTotal: 150 },
      { id: 'item-2', description: '12-Lead Diagnostic Stress Electrocardiogram (ECG)', quantity: 1, unitPrice: 75, lineTotal: 75 },
    ],
    createdAt: '2026-09-18T12:05:00Z',
  },
  {
    id: 'inv-302',
    invoiceNumber: 'INV-2026-102',
    appointmentId: 'apt-105',
    patientId: 'pat-1',
    patientName: 'Eleanor Bennett',
    doctorName: 'Dr. Michael Chen',
    subtotal: 180,
    additionalCharges: 0,
    discount: 18, // 10% wellness discount
    totalAmount: 162,
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    paidAt: '2026-09-15T14:45:00Z',
    dueDate: '2026-09-15',
    items: [
      { id: 'item-3', description: 'Neurology Consultation & Diagnostic Evaluation', quantity: 1, unitPrice: 180, lineTotal: 180 },
    ],
    createdAt: '2026-09-15T14:38:00Z',
  },
  {
    id: 'inv-303',
    invoiceNumber: 'INV-2026-103',
    appointmentId: 'apt-101',
    patientId: 'pat-1',
    patientName: 'Eleanor Bennett',
    doctorName: 'Dr. Sarah Jenkins',
    subtotal: 150,
    additionalCharges: 35, // Basic lab screening
    discount: 0,
    totalAmount: 185,
    paymentStatus: 'unpaid',
    dueDate: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    items: [
      { id: 'item-4', description: 'Consultation Fee - Cardiology', quantity: 1, unitPrice: 150, lineTotal: 150 },
      { id: 'item-5', description: 'Routine BP & Metabolic Panel Fee', quantity: 1, unitPrice: 35, lineTotal: 35 },
    ],
    createdAt: '2026-09-20T10:05:00Z',
  },
  {
    id: 'inv-304',
    invoiceNumber: 'INV-2026-104',
    appointmentId: 'apt-102',
    patientId: 'pat-2',
    patientName: 'James Alexander Davis',
    doctorName: 'Dr. Robert Alverez',
    subtotal: 160,
    additionalCharges: 40,
    discount: 0,
    totalAmount: 200,
    paymentStatus: 'unpaid',
    dueDate: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
    items: [
      { id: 'item-6', description: 'Orthopedics Rehabilitation Review', quantity: 1, unitPrice: 160, lineTotal: 160 },
      { id: 'item-7', description: 'Lumbar Spine Biomechanical Assessment', quantity: 1, unitPrice: 40, lineTotal: 40 },
    ],
    createdAt: '2026-09-21T09:20:00Z',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-501',
    actorUserId: 'user-admin',
    actorName: 'Dr. Evelyn Vance, MD',
    actorRole: 'administrator',
    action: 'CREATE_DOCTOR_PROFILE',
    resourceType: 'doctor',
    resourceId: 'doc-1',
    metadataJson: { doctorEmail: 'doctor@example.test', department: 'Cardiology' },
    ipAddress: '192.168.1.10',
    createdAt: '2026-09-10T08:30:15Z',
  },
  {
    id: 'log-502',
    actorUserId: 'user-pat-1',
    actorName: 'Eleanor Bennett',
    actorRole: 'patient',
    action: 'BOOK_APPOINTMENT',
    resourceType: 'appointment',
    resourceId: 'apt-101',
    metadataJson: { doctorId: 'doc-1', slot: '09:30', date: '2026-09-27' },
    ipAddress: '172.16.20.4',
    createdAt: '2026-09-20T10:00:22Z',
  },
  {
    id: 'log-503',
    actorUserId: 'user-doc-1',
    actorName: 'Dr. Sarah Jenkins',
    actorRole: 'doctor',
    action: 'RECORD_CLINICAL_CONSULTATION',
    resourceType: 'medical_record',
    resourceId: 'rec-201',
    metadataJson: { patientId: 'pat-4', prescriptionsCount: 3 },
    ipAddress: '192.168.2.45',
    createdAt: '2026-09-18T12:02:11Z',
  },
  {
    id: 'log-504',
    actorUserId: 'user-recep',
    actorName: 'Marcus Sterling',
    actorRole: 'receptionist',
    action: 'RECORD_PAYMENT',
    resourceType: 'invoice',
    resourceId: 'inv-301',
    metadataJson: { paymentMethod: 'credit_card', amount: 225 },
    ipAddress: '192.168.1.15',
    createdAt: '2026-09-18T12:20:45Z',
  },
];
